// ============================================================================
// i18n — native tray and dialog labels.
//
// The dictionary itself lives in src/shared/i18n.ts (single source of truth)
// and is compiled into src-tauri/resources/i18n.json by
// scripts/build-tauri-resources.mjs.
// ============================================================================

use crate::config::ConfigState;
use serde_json::{json, Value};
use std::sync::OnceLock;
use tauri::{AppHandle, Manager};

const I18N_JSON: &str = include_str!("../resources/i18n.json");

/// Parsed once — the dictionaries are static data compiled into the binary.
fn dictionaries() -> &'static Value {
    static DICTS: OnceLock<Value> = OnceLock::new();
    DICTS.get_or_init(|| serde_json::from_str(I18N_JSON).unwrap_or_else(|_| json!({})))
}

/// Look up one string for the given locale (used by the tray and native dialogs).
pub fn translate(locale: &str, key: &str) -> String {
    dictionaries()
        .get(locale)
        .and_then(|dict| dict.get(key))
        .and_then(|value| value.as_str())
        .unwrap_or(key)
        .to_string()
}

/// The active locale plus its dictionary, for the renderer's own i18n runtime.
///
/// The lite pages translate themselves (src/renderer/lite-i18n.ts) rather than
/// receiving pre-translated strings, so switching the language is a single
/// `config_set` and the pages re-fetch this.
#[tauri::command]
pub fn i18n_get(app: AppHandle) -> Value {
    let locale = app
        .try_state::<ConfigState>()
        .and_then(|state| state.get("locale").as_str().map(str::to_string))
        .unwrap_or_else(|| "zh".to_string());
    let dict = dictionaries()
        .get(&locale)
        .cloned()
        .unwrap_or_else(|| json!({}));
    json!({ "locale": locale, "dict": dict })
}

#[cfg(test)]
mod tests {
    use super::*;

    fn sorted_keys(value: &Value) -> Vec<String> {
        let mut keys: Vec<String> = value
            .as_object()
            .map(|map| map.keys().cloned().collect())
            .unwrap_or_default();
        keys.sort();
        keys
    }

    fn text(locale: &str, key: &str) -> String {
        dictionaries()
            .get(locale)
            .and_then(|dict| dict.get(key))
            .and_then(Value::as_str)
            .unwrap_or_default()
            .to_string()
    }

    /// resources/i18n.json is generated by `npm run build` but committed, so a
    /// forgotten build would ship a dictionary without the newest keys.
    #[test]
    fn ships_the_lightweight_strings_for_both_locales() {
        assert_eq!(text("zh", "lite.menu.quit"), "退出");
        assert_eq!(text("en", "lite.menu.quit"), "Quit");
        assert!(text("zh", "lite.pet.hourlyChime").contains("{h}"));
        assert!(text("en", "lite.drop.multiple").contains("{n}"));
    }

    /// The renderer falls back to the key itself, which would render
    /// "lite.pet.petting" on the pet — so the two locales must stay in step.
    #[test]
    fn both_locales_ship_the_same_keys() {
        let dicts = dictionaries();
        let zh = dicts.get("zh").expect("zh dictionary");
        let en = dicts.get("en").expect("en dictionary");
        assert_eq!(sorted_keys(zh), sorted_keys(en));
    }
}
